name: Validació Markdown

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  validate-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validar fitxers Markdown
        run: |
          markdownlint 
